# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUfDs01ntu3gwXAmdKW_2S5tt1Lx1Vc9
"""

print("SAM AI Technologies - Task 1 Chatbot")

while True:
    user = input("You: ").lower()

    if "hi" in user:
        print("Bot: Hello Pujitha! Welcome to SAM AI")
    elif "help" in user:
        print("Bot: Type hi, help, or bye")
    elif "bye" in user:
        print("Bot: Goodbye from SAM AI")
        break
    else:
        print("Bot: I don't understand. Type 'help'")